// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import AudioToolbox;
@import Dispatch;
@import Foundation;
@import CoreData;
@import CoreGraphics;
@import MessageUI;
@import AVFoundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSURL;
@class NSTimer;

SWIFT_CLASS("_TtC11GulliverEXT11SoundEffect")
@interface SoundEffect : NSObject
+ (NSDictionary<NSString *, SoundEffect *> * __nonnull)cachedSounds;
+ (void)setCachedSounds:(NSDictionary<NSString *, SoundEffect *> * __nonnull)value;
+ (NSArray<SoundEffect *> * __nonnull)playingSounds;
+ (void)setPlayingSounds:(NSArray<SoundEffect *> * __nonnull)value;
+ (SoundEffect * __nullable)soundEffectFromURL:(NSURL * __nonnull)url;
+ (SoundEffect * __nullable)preflightSound:(NSString * __nonnull)name;
+ (BOOL)playSound:(NSString * __nonnull)name;
- (nullable instancetype)initWithUrl:(NSURL * __nullable)url preload:(BOOL)preload OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithName:(NSString * __nonnull)name preload:(BOOL)preload;
- (BOOL)play;
- (void)pause;
@property (nonatomic, readonly) BOOL isPlaying;
@property (nonatomic, weak) NSTimer * __nullable dequeueTimer;
- (void)unregsterAsPlaying;
@end

@class AVAudioPlayer;

SWIFT_CLASS("_TtC11GulliverEXT8WAVSound")
@interface WAVSound : SoundEffect
@property (nonatomic, readonly, strong) NSURL * __null_unspecified URL;
@property (nonatomic, strong) AVAudioPlayer * __null_unspecified player;
@property (nonatomic, readonly, copy) NSString * __nonnull description;
- (nullable instancetype)initWithUrl:(NSURL * __nullable)url preload:(BOOL)preload OBJC_DESIGNATED_INITIALIZER;
- (BOOL)play;
- (void)pause;
@property (nonatomic, readonly) BOOL isPlaying;
@end


SWIFT_CLASS("_TtC11GulliverEXT9AIFFSound")
@interface AIFFSound : WAVSound
- (nullable instancetype)initWithUrl:(NSURL * __nullable)url preload:(BOOL)preload OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;
@class NSAttributedString;
@class NSLayoutConstraint;
@class NSCoder;

SWIFT_CLASS("_TtC11GulliverEXT23AttributedTableViewCell")
@interface AttributedTableViewCell : UITableViewCell
@property (nonatomic, strong) UILabel * __null_unspecified attributedLabel;
@property (nonatomic, strong) NSAttributedString * __nullable attributedText;
@property (nonatomic, copy) NSArray<NSLayoutConstraint *> * __nonnull labelConstraints;
@property (nonatomic) UIEdgeInsets edgeInsets;
- (void)setupConstraints;
- (void)didMoveToSuperview;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11GulliverEXT8CAFSound")
@interface CAFSound : SoundEffect
+ (SystemSoundID)soundIDCount;
+ (void)setSoundIDCount:(SystemSoundID)value;
@property (nonatomic, strong) NSURL * __nullable URL;
- (nullable instancetype)initWithName:(NSString * __nonnull)name preload:(BOOL)preload;
@property (nonatomic, readonly, copy) NSString * __nonnull description;
- (nullable instancetype)initWithUrl:(NSURL * __nullable)url preload:(BOOL)preload OBJC_DESIGNATED_INITIALIZER;
- (BOOL)play;
@end

@class NSBundle;

SWIFT_CLASS("_TtC11GulliverEXT23ContainerViewController")
@interface ContainerViewController : UIViewController
@property (nonatomic, strong) UIViewController * __nullable currentController;
- (nonnull instancetype)initWithInitialViewController:(UIViewController * __nonnull)initialViewController;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSManagedObjectModel;
@class NSPersistentStoreCoordinator;
@class NSManagedObjectContext;
@class NSNotification;

SWIFT_CLASS("_TtC11GulliverEXT18ManagedObjectStore")
@interface ManagedObjectStore : NSObject
@property (nonatomic, readonly, strong) NSManagedObjectModel * __nonnull model;
@property (nonatomic, readonly, strong) NSPersistentStoreCoordinator * __nonnull persistentStoreCoordinator;
@property (nonatomic, strong) NSManagedObjectContext * __null_unspecified mainThreadContext;
@property (nonatomic, readonly, strong) NSManagedObjectContext * __nonnull privateContext;
+ (NSURL * __nullable)modelURL;
+ (void)setModelURL:(NSURL * __nullable)value;
+ (NSString * __nullable)filename;
+ (void)setFilename:(NSString * __nullable)value;
+ (NSURL * __nullable)storeDirectoryURL;
+ (void)setStoreDirectoryURL:(NSURL * __nullable)value;
- (nonnull instancetype)initWithModelURL:(NSURL * __nullable)modelURL filename:(NSString * __nullable)filename options:(NSDictionary<NSString *, id> * __nonnull)opts OBJC_DESIGNATED_INITIALIZER;
- (void)setup;
@property (nonatomic, readonly, strong) dispatch_group_t __null_unspecified saveDispatchGroup;
- (void)contextDidSave:(NSNotification * __nonnull)note;
- (NSManagedObjectContext * __nonnull)createWorkerContext;
- (void)importBlock:(void (^ __nonnull)(NSManagedObjectContext * __nonnull))block;
- (id __nullable)objectForKeyedSubscript:(NSString * __nonnull)key;
- (void)setObject:(id __nullable)newValue forKeyedSubscript:(NSString * __nonnull)key;
@end


@interface NSAttributedString (SWIFT_EXTENSION(GulliverEXT))
- (NSAttributedString * __nonnull)stringByAppendingString:(NSAttributedString * __nonnull)string;
- (NSAttributedString * __nonnull)stringByAppendingString:(NSString * __nonnull)string attributes:(NSDictionary<NSString *, id> * __nonnull)attributes;
@end


@interface NSData (SWIFT_EXTENSION(GulliverEXT))
@property (nonatomic, readonly, copy) NSString * __nonnull hexString;
- (nullable instancetype)initWithHexString:(NSString * __nonnull)hexString;
@property (nonatomic, readonly, copy) NSString * __nullable string;
@end


@interface NSDate (SWIFT_EXTENSION(GulliverEXT))
@end


@interface NSDate (SWIFT_EXTENSION(GulliverEXT))
+ (NSString * __nonnull)ageString:(NSTimeInterval)age style:(NSDateFormatterStyle)style;
@end


@interface NSDate (SWIFT_EXTENSION(GulliverEXT))
- (NSString * __nonnull)localTimeString:(NSDateFormatterStyle)dateStyle timeStyle:(NSDateFormatterStyle)timeStyle;
@property (nonatomic, readonly) BOOL isToday;
@property (nonatomic, readonly) BOOL isTomorrow;
@property (nonatomic, readonly) BOOL isYesterday;
@property (nonatomic, readonly) NSInteger year;
@property (nonatomic, readonly) NSInteger day;
@property (nonatomic, readonly) NSInteger hour;
@property (nonatomic, readonly) NSInteger minute;
@property (nonatomic, readonly) NSInteger second;
@property (nonatomic, readonly, strong) NSDate * __nonnull nextDay;
@property (nonatomic, readonly, strong) NSDate * __nonnull previousDay;
@property (nonatomic, readonly, strong) NSDate * __nonnull firstSecond;
@property (nonatomic, readonly, strong) NSDate * __nonnull lastSecond;
@property (nonatomic, readonly, strong) NSDate * __nonnull noon;
- (BOOL)isAfter:(NSDate * __nonnull)date;
- (BOOL)isBefore:(NSDate * __nonnull)date;
- (BOOL)isSameDayAs:(NSDate * __nonnull)other;
@end


@interface NSError (SWIFT_EXTENSION(GulliverEXT))
@property (nonatomic, readonly) BOOL isTimeout;
@property (nonatomic, readonly) BOOL isNoConnection;
@property (nonatomic, readonly, copy) NSArray<NSError *> * __nonnull underlyingErrors;
@end


@interface NSFileManager (SWIFT_EXTENSION(GulliverEXT))
- (BOOL)fileExistsAtURL:(NSURL * __nonnull)url;
- (BOOL)directoryExistsAtURL:(NSURL * __nonnull)url;
+ (NSURL * __nullable)userDirectory:(NSSearchPathDirectory)type;
+ (NSURL * __nonnull)documentsDirectoryURL;
+ (NSURL * __nonnull)libraryDirectoryURL;
+ (NSURL * __nonnull)applicationSupportDirectoryURL;
+ (NSURL * __nonnull)cachesDirectoryURL;
+ (NSURL * __nonnull)tempDirectoryURL;
@end

@class ThreadsafeToken;

@interface NSManagedObject (SWIFT_EXTENSION(GulliverEXT))
@property (nonatomic, readonly, strong) ThreadsafeToken * __nonnull threadsafeToken;
@end


@interface NSManagedObject (SWIFT_EXTENSION(GulliverEXT))
- (void)importDictionary:(NSDictionary<NSString *, id> * __nonnull)dict;
- (void)importRelationship:(NSString * __nonnull)name fromDictionary:(NSDictionary<NSString *, id> * __nonnull)dict;
- (NSManagedObject * __nullable)findExistingRelationship:(NSString * __nonnull)entityName forDictionary:(NSDictionary<NSString *, id> * __nonnull)dict;
- (NSManagedObject * __nullable)addRelationship:(NSString * __nonnull)name fromDictionary:(NSDictionary<NSString *, id> * __nonnull)dict;
- (NSString * __nullable)dictionaryKeyToAttributeName:(NSString * __nonnull)key;
- (NSDate * __nullable)dictionaryStringToDate:(NSString * __nonnull)string;
@end


@interface NSManagedObject (SWIFT_EXTENSION(GulliverEXT))
- (id __nullable)objectForKeyedSubscript:(NSString * __nonnull)key;
- (void)setObject:(id __nullable)newValue forKeyedSubscript:(NSString * __nonnull)key;
@property (nonatomic, readonly, strong) NSManagedObjectContext * __nullable moc;
- (NSManagedObject * __nullable)objectInContext:(NSManagedObjectContext * __nonnull)moc;
- (void)log;
- (void)refreshInContext:(BOOL)merge;
+ (NSString * __nonnull)entityName;
- (void)deleteFromContext;
- (BOOL)hasPropertyForKey:(NSString * __nonnull)key;
@end


@interface NSManagedObjectContext (SWIFT_EXTENSION(GulliverEXT))
@end

@class NSFetchRequest;

@interface NSManagedObjectContext (SWIFT_EXTENSION(GulliverEXT))
- (NSManagedObject * __nonnull)insertEntityNamed:(NSString * __nonnull)name;
- (void)saveAndWait:(BOOL)wait toDisk:(BOOL)toDisk completion:(void (^ __nullable)(NSError * __nullable))completion;
- (void)refreshAllFaults;
- (NSFetchRequest * __nonnull)fetchRequest:(NSString * __nonnull)name;
@end


@interface NSMutableAttributedString (SWIFT_EXTENSION(GulliverEXT))
- (void)addLineBreakOfHeight:(CGFloat)height;
@end


@interface NSMutableAttributedString (SWIFT_EXTENSION(GulliverEXT))
@end


@interface NSMutableAttributedString (SWIFT_EXTENSION(GulliverEXT))
- (void)appendString:(NSString * __nonnull)string attributes:(NSDictionary<NSString *, id> * __nonnull)attributes;
- (void)assignAttributes:(NSDictionary<NSString *, id> * __nonnull)attr toUniqueSubstring:(NSString * __nonnull)text;
@end

@class NSDictionary;

@interface NSNotification (SWIFT_EXTENSION(GulliverEXT))
+ (void)postNotification:(NSString * __nonnull)name object:(id __nullable)object userInfo:(NSDictionary * __nullable)userInfo;
+ (void)postNotificationOnMainThread:(NSString * __nonnull)name object:(id __nullable)object userInfo:(NSDictionary * __nullable)userInfo;
@end


@interface NSObject (SWIFT_EXTENSION(GulliverEXT))
- (void)addAsObserver:(NSString * __nonnull)name selector:(NSString * __nonnull)selector object:(id __nullable)object;
- (void)removeAsObserver;
@end


@interface NSOperationQueue (SWIFT_EXTENSION(GulliverEXT))
- (nonnull instancetype)initWithSerial:(BOOL)serial;
- (void)addOperationWithBlockAndWait:(void (^ __nonnull)(void))block;
@end

@class NSMutableParagraphStyle;

@interface NSParagraphStyle (SWIFT_EXTENSION(GulliverEXT))
+ (NSMutableParagraphStyle * __nonnull)aligned:(NSTextAlignment)alignment;
@end


@interface NSUserDefaults (SWIFT_EXTENSION(GulliverEXT))
+ (void)setCurrentDefaultsGroup:(NSString * __nonnull)group;
+ (NSUserDefaults * __nonnull)defaults;
+ (BOOL)hasValueForKey:(NSString * __nonnull)key;
+ (void)removeValueForKey:(NSString * __nonnull)key;
@end


@interface NSUserDefaults (SWIFT_EXTENSION(GulliverEXT))
- (BOOL)hasValueForKey:(NSString * __nonnull)key;
- (void)removeValueForKey:(NSString * __nonnull)key;
@end

@protocol NSObject;
@class Watcher;

SWIFT_CLASS("_TtC11GulliverEXT8Notifier")
@interface Notifier : NSObject
@property (nonatomic, readonly, copy) NSString * __nonnull name;
- (nonnull instancetype)init:(NSString * __nonnull)nm OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) NSOperationQueue * __nonnull serializer;
- (void)unwatch:(NSObject * __nonnull)observer object:(NSObject * __nullable)object;
- (void)notify:(NSObject * __nullable)object info:(NSDictionary * __nullable)info forceCurrentThread:(BOOL)forceCurrentThread;
- (void)unwatch:(id <NSObject> __nonnull)token;
@property (nonatomic, copy) NSArray<Watcher *> * __nonnull watchers;
- (void)unregister:(Watcher * __nonnull)watcher;
- (void)clean:(BOOL)serialized;
@end


@interface Notifier (SWIFT_EXTENSION(GulliverEXT))
@end


SWIFT_CLASS("_TtC11GulliverEXT28SA_MailComposeViewController")
@interface SA_MailComposeViewController : MFMailComposeViewController <MFMailComposeViewControllerDelegate>
@property (nonatomic, copy) void (^ __nullable completion)(MFMailComposeResult);
- (nullable instancetype)initToAddress:(NSString * __nonnull)toAddress subject:(NSString * __nullable)subject body:(NSString * __nullable)body completion:(void (^ __nullable)(MFMailComposeResult))comp;
- (void)mailComposeController:(MFMailComposeViewController * __nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * __nullable)error;
- (nonnull instancetype)initWithNavigationBarClass:(Class __nullable)navigationBarClass toolbarClass:(Class __nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRootViewController:(UIViewController * __nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class UIView;

SWIFT_CLASS("_TtC11GulliverEXT16SA_TableViewCell")
@interface SA_TableViewCell : UITableViewCell
@property (nonatomic, strong) UIColor * __nullable dividerColor;
@property (nonatomic, strong) UIView * __nullable dividerView;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@class NSMutableArray;

SWIFT_CLASS("_TtC11GulliverEXT11SoundPlayer")
@interface SoundPlayer : NSObject <AVAudioPlayerDelegate>
+ (SoundPlayer * __nonnull)player;
@property (nonatomic, strong) NSMutableArray * __nonnull players;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)playWAV:(NSString * __nonnull)name directory:(NSString * __nullable)directory;
- (BOOL)play:(NSString * __nonnull)name directory:(NSString * __nullable)directory;
- (BOOL)playAIFF:(NSString * __nonnull)name directory:(NSString * __nullable)directory;
- (BOOL)playSoundAtURL:(NSURL * __nonnull)url;
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * __nonnull)player successfully:(BOOL)flag;
@end


@interface UIBezierPath (SWIFT_EXTENSION(GulliverEXT))
- (void)appendString:(NSAttributedString * __nonnull)string atPoint:(CGPoint)pt withTransform:(CGAffineTransform)withTransform;
@end

@class UITapGestureRecognizer;

SWIFT_CLASS("_TtC11GulliverEXT14UIBlockingView")
@interface UIBlockingView : UIView
@property (nonatomic, copy) void (^ __nullable tappedClosure)(void);
- (void)tapped:(UITapGestureRecognizer * __nonnull)recog;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(GulliverEXT))
- (nullable instancetype)initWithHex:(NSString * __nonnull)hex;
@property (nonatomic, readonly, copy) NSString * __nonnull hex;
@end


@interface UIDevice (SWIFT_EXTENSION(GulliverEXT))
@property (nonatomic, readonly) BOOL isIPad;
@end


@interface UIFont (SWIFT_EXTENSION(GulliverEXT))
- (CGSize)sizeOfString:(NSString * __nonnull)string constrainedToWidth:(CGFloat)width;
@end


@interface UIImage (SWIFT_EXTENSION(GulliverEXT))
- (UIImage * __nonnull)tintedImage:(UIColor * __nonnull)tint;
- (UIImage * __nonnull)scaledImage:(CGFloat)scale;
- (UIImage * __nonnull)resizedImage:(CGSize)size trimmed:(BOOL)trimmed;
+ (UIImage * __nullable)deviceLaunchImage:(UIDeviceOrientation)orientation;
+ (NSURL * __nullable)deviceLaunchImageURL:(UIDeviceOrientation)orientation;
@end


@interface UIImageView (SWIFT_EXTENSION(GulliverEXT))
+ (UIImageView * __nullable)deviceLaunchImageView:(UIInterfaceOrientation)orientation;
@end


@interface UILabel (SWIFT_EXTENSION(GulliverEXT))
@property (nonatomic, readonly, strong) UIFont * __nonnull actualFontInUse;
@end


@interface UIScrollView (SWIFT_EXTENSION(GulliverEXT))
@property (nonatomic) BOOL resizesForKeyboard;
- (void)gulliver_keyboardWillShow:(NSNotification * __nonnull)note;
- (void)gulliver_keyboardWillHide:(NSNotification * __nonnull)note;
@end


@interface UIView (SWIFT_EXTENSION(GulliverEXT))
+ (UIView * __nullable)view:(NSString * __nullable)nibName bundle:(NSBundle * __nonnull)bundle;
@property (nonatomic, readonly) CGPoint contentCenter;
- (void)resignFirstResponderForAllSubviews;
- (UIView * __nonnull)blockingViewWithTappedClosure:(void (^ __nullable)(void))closure;
@property (nonatomic, readonly, strong) UIViewController * __nullable viewController;
@property (nonatomic, readonly, strong) UITableViewCell * __nullable tableViewCell;
- (NSString * __nonnull)hierarchy:(NSString * __nullable)prefix;
- (BOOL)isAncestor:(UIView * __nullable)view;
@end


@interface UIView (SWIFT_EXTENSION(GulliverEXT))
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat width;
@property (nonatomic) CGFloat height;
@property (nonatomic) CGPoint origin;
@property (nonatomic) CGSize size;
@end


#pragma clang diagnostic pop
